---
name: MooseX-FollowPBP
version: 0.02
author:
  - 'Dave Rolsky, C<< <autarch@urth.org> >>'
abstract: Name your accessors get_foo() and set_foo()
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Moose: 0.56
build_requires:
  Test::More: 0
provides:
  MooseX::FollowPBP:
    file: lib/MooseX/FollowPBP.pm
    version: 0.02
  MooseX::FollowPBP::Role::Attribute:
    file: lib/MooseX/FollowPBP/Role/Attribute.pm
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
